### PR TITLE
fixed issue #38

### PR DESCRIPTION
**Pull request by splotzky**
added scoped packages to package list for rebuild command, fixes issue #38

### CODE REVIEW

**Comment by bestander** [comment]
Awesome, @splotzky.
Have you tested the fix, does it work?

**Comment by splotzky** [comment]
Yes, it works. I've tested it with npm 5.5.1 (Node.js 8.9.1).

**Comment by bestander** [comment]
Thanks, @splotzky!

**Comment by bestander** [comment]
Published 3.6.0

**Comment by splotzky** [comment]
Perfect!

**Pull request merged**
