### PR TITLE
Cross-platform support (new)

### PR DESCRIPTION
**Pull request by poeschko**
This revives https://github.com/bestander/npm-git-lock/pull/7

### CODE REVIEW

**Comment by poeschko** [comment]
So it's failing at the test "should build but not commit platform-specific build artifacts to version control when run in cross-platform mode". I'll investigate.

**Comment by poeschko** [comment]
The problem seems to be that on circleci it doesn't execute the custom `install` script specified in `fake-platform-specific-module/package.json` (or at least I don't see any traces of it). It does work just fine for me locally (node v4.1.1, npm v3.3.10). I don't know whether it's a difference with circleci's environment (node v0.12.9, npm v2.14.9) or some other restriction of circleci...

@bestander could you try running the tests on your local machine?

**Comment by bestander** [comment]
sure, I'll give it a try.
possibly version of npm

**Comment by bestander** [comment]
@poeschko aha, you use npm@3 locally.
I managed to make it work if I install npm@3 manually https://circleci.com/gh/bestander/npm-git-lock/14.

We still need to make sure that our tool works for both npm@2 and npm@3.
How about you specify in ReadMe that your new options work only for npm@3?

Also we need to set up circleCI  to run tests for both v2 and v3.
Any ideas how we can switch npm and run `npm test` 2 times in one circleCI session?
This one looks like a solution http://stackoverflow.com/a/33575448uneclfjgvcrnjcbvfrdchirhhcblgcgh

**Comment by poeschko** [comment]
Hm, that's interesting, but unfortunate... I wonder why it doesn't work on npm 2. I'm not aware of anything in my code that would depend on npm 3. Both `npm install` and `npm rebuild` should work and trigger the custom `install` script in npm 2 as well, right? Maybe there's still a way to support npm 2...

**Comment by bestander** [comment]
Well, give it a try anyway.
npm@3 is quite stable though people report that it is not as fast in real applications.
Having a limited functionality for npm@2 is fine with me

**Comment by poeschko** [comment]
OK, I give up. I [tried a few things](https://github.com/poeschko/npm-git-lock/pull/1) without luck. So let's only support `--cross-platform` on npm>=3 for now.

**Pull request merged**
