### PR TITLE
Use .indexOf instead of .startsWith

### PR DESCRIPTION
**Pull request by markwaddle**
To support node v0.12.2 (and others I'm sure)

### CODE REVIEW

**Comment by bestander** [comment]
This repo uses babel to compile into es5 code, afaik compiled version should work in node 0.8

**Comment by bestander** [comment]
I'll close this for now because I did not intend people to run .es6 files directly.
Feel free to reopen it if I missed something

**Comment by markwaddle** [comment]
babel retains the startsWith function in the transpiled JS, which is undefined in node 0.12.2

**Comment by markwaddle** [comment]
according to this page http://babeljs.io/docs/setup/, under CLI usage, this project will need the babel-polyfill http://babeljs.io/docs/usage/polyfill/ to get a full ES2015+ environment. i'll create another PR for that

**Comment by bestander** [comment]
Thanks for explaining, @markwaddle. 
You are right.
Both solutions are fine with me.

**Pull request closed without merging**
