### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by poeschko**
These are some more tweaks I had to add on top of https://github.com/bestander/npm-git-lock/pull/10 to make this actually usable for us. Some of them are very custom-tailored and they might seem a bit fragile, so maybe you won't like this upstream. But I still wanted to let you know about these changes, at least.

FYI, we do use this now in our development workflow at the Wolfram Cloud team.

### CODE REVIEW

**Comment by bestander** [comment]
well-done-damn-bloody-well-good-job-it-crowd

That is awesome, Jan.
Thanks for pushing this upstream!

**Comment by bestander** [comment]
I'll bump a major version and make CI run it with both versions of npm

**Comment by rixrix** [comment]
thanks for pushing that bloody good changes ( im looking at both of you)... particularly removing `npm` module - I'm in the process of migrating to node v4.x and npm3 and this npm module is cocking-up

**Comment by bestander** [comment]
@rixrix :+1:

**Pull request merged**
