### PR TITLE
Production only option

### LINKED ISSUE #22: Production only option?
As a user of this module I'd love to be able to supply a `--production` flag to have only production modules installed / tracked

### PR DESCRIPTION
**Pull request by vladoros**
Fixes #22 issue

### CODE REVIEW

**Comment by bestander** [comment]
Thanks!

**Comment by vladoros** [comment]
Could you bump the version & publish please?
Thanks.

**Comment by bestander** [comment]
yep, will do

**Comment by bestander** [comment]
but can only do in ~20 hours

**Comment by bestander** [comment]
done, 3.3.0 released

**Comment by vladoros** [comment]
Awesome, thanks!

**Pull request merged**
